all:
  hosts:
    jw1:   { ansible_host: 10.254.202.81,  ansible_port: 22, ansible_user: kcloud, ansible_password: "{{ lookup('env','SUDO_PASS') }}", ansible_become_password: "{{ lookup('env','SUDO_PASS') }}", etcd_member_name: etcd1 }
    jw2:   { ansible_host: 10.254.202.82,  ansible_port: 22, ansible_user: kcloud, ansible_password: "{{ lookup('env','SUDO_PASS') }}", ansible_become_password: "{{ lookup('env','SUDO_PASS') }}" }
    jw3:   { ansible_host: 10.254.202.83,  ansible_port: 22, ansible_user: kcloud, ansible_password: "{{ lookup('env','SUDO_PASS') }}", ansible_become_password: "{{ lookup('env','SUDO_PASS') }}" }
    node4: { ansible_host: 10.254.202.114, ansible_port: 22, ansible_user: kcloud, ansible_password: "{{ lookup('env','SUDO_PASS') }}", ansible_become_password: "{{ lookup('env','SUDO_PASS') }}" }
  children:
    kube_control_plane: { hosts: { jw1: {} } }
    etcd:               { hosts: { jw1: {} } }
    kube_node:          { hosts: { jw1: {}, jw2: {}, jw3: {}, node4: {} } }
    k8s_cluster:        { children: { kube_control_plane: {}, kube_node: {} } }
    calico_rr:          { hosts: {} }
