// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: exam.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "";

export interface CreateExamReq {
  id: string;
  benchmark: string;
  resource: ExamResource | undefined;
  scenario: ExamScenario | undefined;
  settings: ExamSettings | undefined;
}

export interface ExamSettings {
  nTrain: string;
  modelName: string;
  datasetName: string;
  precision: string;
  maxTestSamples: string;
  framework: string;
  selectedSubjects: string;
  gpuUtil: string;
  batchSize: string;
  totalSampleCount: string;
  mode: string;
  scenario: string;
  serverTargetQps: string;
  numWorkers: string;
  minDuration: string;
  tensorParallelSize: string;
  extraArg: string;
}

export interface ExamResource {
  cpu: number;
  gpuModel: string;
  gpuCount: number;
  memory: number;
}

export interface ExamScenario {
  startTime: string;
  repeatCount: number;
}

export interface CreateExamRes {
  message: string;
}

export interface GetExamStatusReq {
  id: string;
  benchmark: string;
}

export interface GetExamStatusRes {
  status: string;
  message: string;
  currentRepeatCount: string;
}

export interface DeleteExamReq {
  id: string;
  benchmark: string;
}

export interface DeleteExamRes {
  message: string;
}

export interface UpdateExamStartTimeReq {
  id: string;
  benchmark: string;
  startTime: string;
}

export interface UpdateExamStartTimeRes {
  message: string;
}

export interface GetAvailableGPUsRes {
  gpus: GPUInfo[];
}

export interface GPUInfo {
  gpuModel: string;
  gpuCount: number;
}

export const _PACKAGE_NAME = "";

function createBaseCreateExamReq(): CreateExamReq {
  return { id: "", benchmark: "", resource: undefined, scenario: undefined, settings: undefined };
}

export const CreateExamReq: MessageFns<CreateExamReq> = {
  encode(message: CreateExamReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.benchmark !== "") {
      writer.uint32(18).string(message.benchmark);
    }
    if (message.resource !== undefined) {
      ExamResource.encode(message.resource, writer.uint32(26).fork()).join();
    }
    if (message.scenario !== undefined) {
      ExamScenario.encode(message.scenario, writer.uint32(34).fork()).join();
    }
    if (message.settings !== undefined) {
      ExamSettings.encode(message.settings, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateExamReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateExamReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.benchmark = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resource = ExamResource.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.scenario = ExamScenario.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.settings = ExamSettings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseExamSettings(): ExamSettings {
  return {
    nTrain: "",
    modelName: "",
    datasetName: "",
    precision: "",
    maxTestSamples: "",
    framework: "",
    selectedSubjects: "",
    gpuUtil: "",
    batchSize: "",
    totalSampleCount: "",
    mode: "",
    scenario: "",
    serverTargetQps: "",
    numWorkers: "",
    minDuration: "",
    tensorParallelSize: "",
    extraArg: "",
  };
}

export const ExamSettings: MessageFns<ExamSettings> = {
  encode(message: ExamSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nTrain !== "") {
      writer.uint32(10).string(message.nTrain);
    }
    if (message.modelName !== "") {
      writer.uint32(18).string(message.modelName);
    }
    if (message.datasetName !== "") {
      writer.uint32(26).string(message.datasetName);
    }
    if (message.precision !== "") {
      writer.uint32(34).string(message.precision);
    }
    if (message.maxTestSamples !== "") {
      writer.uint32(42).string(message.maxTestSamples);
    }
    if (message.framework !== "") {
      writer.uint32(50).string(message.framework);
    }
    if (message.selectedSubjects !== "") {
      writer.uint32(58).string(message.selectedSubjects);
    }
    if (message.gpuUtil !== "") {
      writer.uint32(66).string(message.gpuUtil);
    }
    if (message.batchSize !== "") {
      writer.uint32(74).string(message.batchSize);
    }
    if (message.totalSampleCount !== "") {
      writer.uint32(82).string(message.totalSampleCount);
    }
    if (message.mode !== "") {
      writer.uint32(90).string(message.mode);
    }
    if (message.scenario !== "") {
      writer.uint32(98).string(message.scenario);
    }
    if (message.serverTargetQps !== "") {
      writer.uint32(106).string(message.serverTargetQps);
    }
    if (message.numWorkers !== "") {
      writer.uint32(114).string(message.numWorkers);
    }
    if (message.minDuration !== "") {
      writer.uint32(122).string(message.minDuration);
    }
    if (message.tensorParallelSize !== "") {
      writer.uint32(130).string(message.tensorParallelSize);
    }
    if (message.extraArg !== "") {
      writer.uint32(138).string(message.extraArg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExamSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExamSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nTrain = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.datasetName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.precision = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.maxTestSamples = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.framework = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.selectedSubjects = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.gpuUtil = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.batchSize = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.totalSampleCount = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.mode = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.scenario = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.serverTargetQps = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.numWorkers = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.minDuration = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.tensorParallelSize = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.extraArg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseExamResource(): ExamResource {
  return { cpu: 0, gpuModel: "", gpuCount: 0, memory: 0 };
}

export const ExamResource: MessageFns<ExamResource> = {
  encode(message: ExamResource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cpu !== 0) {
      writer.uint32(8).int32(message.cpu);
    }
    if (message.gpuModel !== "") {
      writer.uint32(18).string(message.gpuModel);
    }
    if (message.gpuCount !== 0) {
      writer.uint32(24).int32(message.gpuCount);
    }
    if (message.memory !== 0) {
      writer.uint32(32).int32(message.memory);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExamResource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExamResource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cpu = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.gpuModel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.gpuCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.memory = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseExamScenario(): ExamScenario {
  return { startTime: "", repeatCount: 0 };
}

export const ExamScenario: MessageFns<ExamScenario> = {
  encode(message: ExamScenario, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startTime !== "") {
      writer.uint32(10).string(message.startTime);
    }
    if (message.repeatCount !== 0) {
      writer.uint32(16).int32(message.repeatCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExamScenario {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExamScenario();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.startTime = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.repeatCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateExamRes(): CreateExamRes {
  return { message: "" };
}

export const CreateExamRes: MessageFns<CreateExamRes> = {
  encode(message: CreateExamRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateExamRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateExamRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetExamStatusReq(): GetExamStatusReq {
  return { id: "", benchmark: "" };
}

export const GetExamStatusReq: MessageFns<GetExamStatusReq> = {
  encode(message: GetExamStatusReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.benchmark !== "") {
      writer.uint32(18).string(message.benchmark);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExamStatusReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExamStatusReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.benchmark = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetExamStatusRes(): GetExamStatusRes {
  return { status: "", message: "", currentRepeatCount: "" };
}

export const GetExamStatusRes: MessageFns<GetExamStatusRes> = {
  encode(message: GetExamStatusRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.currentRepeatCount !== "") {
      writer.uint32(26).string(message.currentRepeatCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetExamStatusRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetExamStatusRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currentRepeatCount = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteExamReq(): DeleteExamReq {
  return { id: "", benchmark: "" };
}

export const DeleteExamReq: MessageFns<DeleteExamReq> = {
  encode(message: DeleteExamReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.benchmark !== "") {
      writer.uint32(18).string(message.benchmark);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteExamReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteExamReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.benchmark = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteExamRes(): DeleteExamRes {
  return { message: "" };
}

export const DeleteExamRes: MessageFns<DeleteExamRes> = {
  encode(message: DeleteExamRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteExamRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteExamRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateExamStartTimeReq(): UpdateExamStartTimeReq {
  return { id: "", benchmark: "", startTime: "" };
}

export const UpdateExamStartTimeReq: MessageFns<UpdateExamStartTimeReq> = {
  encode(message: UpdateExamStartTimeReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.benchmark !== "") {
      writer.uint32(18).string(message.benchmark);
    }
    if (message.startTime !== "") {
      writer.uint32(26).string(message.startTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateExamStartTimeReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateExamStartTimeReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.benchmark = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateExamStartTimeRes(): UpdateExamStartTimeRes {
  return { message: "" };
}

export const UpdateExamStartTimeRes: MessageFns<UpdateExamStartTimeRes> = {
  encode(message: UpdateExamStartTimeRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateExamStartTimeRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateExamStartTimeRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetAvailableGPUsRes(): GetAvailableGPUsRes {
  return { gpus: [] };
}

export const GetAvailableGPUsRes: MessageFns<GetAvailableGPUsRes> = {
  encode(message: GetAvailableGPUsRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.gpus) {
      GPUInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAvailableGPUsRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAvailableGPUsRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gpus.push(GPUInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGPUInfo(): GPUInfo {
  return { gpuModel: "", gpuCount: 0 };
}

export const GPUInfo: MessageFns<GPUInfo> = {
  encode(message: GPUInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gpuModel !== "") {
      writer.uint32(10).string(message.gpuModel);
    }
    if (message.gpuCount !== 0) {
      writer.uint32(16).int32(message.gpuCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GPUInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGPUInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gpuModel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gpuCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface ExamServiceClient {
  createExam(request: CreateExamReq): Observable<CreateExamRes>;

  getExamStatus(request: GetExamStatusReq): Observable<GetExamStatusRes>;

  deleteExam(request: DeleteExamReq): Observable<DeleteExamRes>;

  updateExamStartTime(request: UpdateExamStartTimeReq): Observable<UpdateExamStartTimeRes>;

  getAvailableGpUs(request: Empty): Observable<GetAvailableGPUsRes>;
}

export interface ExamServiceController {
  createExam(request: CreateExamReq): Promise<CreateExamRes> | Observable<CreateExamRes> | CreateExamRes;

  getExamStatus(request: GetExamStatusReq): Promise<GetExamStatusRes> | Observable<GetExamStatusRes> | GetExamStatusRes;

  deleteExam(request: DeleteExamReq): Promise<DeleteExamRes> | Observable<DeleteExamRes> | DeleteExamRes;

  updateExamStartTime(
    request: UpdateExamStartTimeReq,
  ): Promise<UpdateExamStartTimeRes> | Observable<UpdateExamStartTimeRes> | UpdateExamStartTimeRes;

  getAvailableGpUs(
    request: Empty,
  ): Promise<GetAvailableGPUsRes> | Observable<GetAvailableGPUsRes> | GetAvailableGPUsRes;
}

export function ExamServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createExam",
      "getExamStatus",
      "deleteExam",
      "updateExamStartTime",
      "getAvailableGpUs",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ExamService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ExamService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EXAM_SERVICE_NAME = "ExamService";

export type ExamServiceService = typeof ExamServiceService;
export const ExamServiceService = {
  createExam: {
    path: "/ExamService/CreateExam",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateExamReq): Buffer => Buffer.from(CreateExamReq.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateExamReq => CreateExamReq.decode(value),
    responseSerialize: (value: CreateExamRes): Buffer => Buffer.from(CreateExamRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateExamRes => CreateExamRes.decode(value),
  },
  getExamStatus: {
    path: "/ExamService/GetExamStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetExamStatusReq): Buffer => Buffer.from(GetExamStatusReq.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetExamStatusReq => GetExamStatusReq.decode(value),
    responseSerialize: (value: GetExamStatusRes): Buffer => Buffer.from(GetExamStatusRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetExamStatusRes => GetExamStatusRes.decode(value),
  },
  deleteExam: {
    path: "/ExamService/DeleteExam",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteExamReq): Buffer => Buffer.from(DeleteExamReq.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteExamReq => DeleteExamReq.decode(value),
    responseSerialize: (value: DeleteExamRes): Buffer => Buffer.from(DeleteExamRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteExamRes => DeleteExamRes.decode(value),
  },
  updateExamStartTime: {
    path: "/ExamService/UpdateExamStartTime",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateExamStartTimeReq): Buffer =>
      Buffer.from(UpdateExamStartTimeReq.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateExamStartTimeReq => UpdateExamStartTimeReq.decode(value),
    responseSerialize: (value: UpdateExamStartTimeRes): Buffer =>
      Buffer.from(UpdateExamStartTimeRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateExamStartTimeRes => UpdateExamStartTimeRes.decode(value),
  },
  getAvailableGpUs: {
    path: "/ExamService/GetAvailableGPUs",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: GetAvailableGPUsRes): Buffer => Buffer.from(GetAvailableGPUsRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetAvailableGPUsRes => GetAvailableGPUsRes.decode(value),
  },
} as const;

export interface ExamServiceServer extends UntypedServiceImplementation {
  createExam: handleUnaryCall<CreateExamReq, CreateExamRes>;
  getExamStatus: handleUnaryCall<GetExamStatusReq, GetExamStatusRes>;
  deleteExam: handleUnaryCall<DeleteExamReq, DeleteExamRes>;
  updateExamStartTime: handleUnaryCall<UpdateExamStartTimeReq, UpdateExamStartTimeRes>;
  getAvailableGpUs: handleUnaryCall<Empty, GetAvailableGPUsRes>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
