{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .components.etriLLMOperator.metadata.name }}
  namespace: {{ .global.namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: etri-llm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/instance: {{ .components.etriLLMOperator.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .components.etriLLMOperator.metadata.name }}
  replicas: 1      
  template:
    metadata:
      labels:
        app: {{ .components.etriLLMOperator.metadata.name }}
        app.kubernetes.io/instance: {{ .components.etriLLMOperator.metadata.name }}
    spec:
      serviceAccountName: {{ .components.etriLLMOperator.metadata.name }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .components.etriLLMOperator.metadata.name }}
          ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP        
          image: {{ .components.etriLLMOperator.containers.image }}
          envFrom:
          - secretRef:
              name: {{ .components.etriLLMOperator.metadata.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "ALL"     
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10        
      imagePullSecrets:
      - name: {{ .global.imagePullSecret.metadata.name }}
{{- end }}