apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: npu

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: etri-llm
  accelerator.etri/vendor: rebellions
  accelerator.etri/family: atomplus
