all:
  hosts:
    jw1:
      ansible_host: 10.254.202.81
      ansible_port: 22
      ansible_user: kcloud
      ansible_password: "{{ lookup('env', 'SUDO_PASS') }}"
      ansible_become_password: "{{ lookup('env', 'SUDO_PASS') }}"

    jw2:
      ansible_host: 10.254.202.82
      ansible_port: 22
      ansible_user: kcloud
      ansible_password: "{{ lookup('env', 'SUDO_PASS') }}"
      ansible_become_password: "{{ lookup('env', 'SUDO_PASS') }}"
      node_labels:
        accelerator: "nvidia-a30"

    jw3:
      ansible_host: 10.254.202.83
      ansible_port: 22
      ansible_user: kcloud
      ansible_password: "{{ lookup('env', 'SUDO_PASS') }}"
      ansible_become_password: "{{ lookup('env', 'SUDO_PASS') }}"
      node_labels:
        accelerator: "nvidia-a30"

  children:
    kube_control_plane:
      hosts:
        jw1:

    kube_node:
      hosts:
        jw2:
        jw3:

    etcd:
      hosts:
        jw1:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}
