global:
  namespace: llm-evaluation
  imagePullSecret:
    metadata:
      name: "image-pull-secret"
    dockerConfigJson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImFuVnVaM2R2YjNOb2FXMDZaR05yY2w5d1lYUmZOR0ZsVmxSb1VIcHZUMlpZZVdOdWRtaDBhVkY2WnpKWE9UVlIifX19

components:
  etriLLMAPI:
    metadata:
      name: "etri-llm-api"
    containers:
      image: "mondrianai/etri-llm-k8s-api:v1.0.0"
      containerPort: "9090"
    service:
      type: "ClusterIP"
      protocol: "TCP"
    secret:
      address: "0.0.0.0"
      logLevel: "info"
      logFileDirPath: "./"
      logMaxSize: "500"
      logMaxAge: "30"
      lokiAddr: "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"

  etriLLMOperator:
    metadata:
      name: "etri-llm-operator"
    containers:
      image: "mondrianai/etri-llm-k8s-operator:v1.0.1"
  
  etriLLMFrontend:
    metadata:
      name: "etri-llm-frontend"
    containers:
      image: "jungwooshim/etri-cloud-frontend:v1.0.0"
      containerPort: "5173"
    service:
      type: "NodePort"
      protocol: "TCP"
      nodePort: "30001"

  etriLLMBackend:
    metadata:
      name: "etri-llm-backend"
    containers:
      image: "jungwooshim/etri-cloud-backend:latest"
      containerPort: "9999"
    service:
      protocol: "TCP"
    

