{{- with .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .components.etriLLMBackend.metadata.name }}
  namespace: {{ .global.namespace }}
type: Opaque
stringData:
  PORT: "9999"
  NODE_ENV: "development"
  GRPC_IP: "etri-llm-api-service.llm-evaluation.svc.cluster.local:9090"
  GRPC_CLIENT_NAME: "EXAM_PACKAGE"
  DATABASE_HOST: etri-llm-db-service.llm-evaluation.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_USER: postgres
  DATABASE_PASSWORD: <DB_PASSWORD>
  DATABASE_NAME: llmEvaluationDB
  LOKI_URL: http://loki.loki.svc.cluster.local:3100
{{- end }}
