apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
    nfd.node.kubernetes.io/feature-labels: cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AMXFP8,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BF16,cpu-cpuid.AVX512BITALG,cpu-cpuid.AVX512BW,cpu-cpuid.AVX512CD,cpu-cpuid.AVX512DQ,cpu-cpuid.AVX512F,cpu-cpuid.AVX512IFMA,cpu-cpuid.AVX512VBMI,cpu-cpuid.AVX512VBMI2,cpu-cpuid.AVX512VL,cpu-cpuid.AVX512VNNI,cpu-cpuid.AVX512VPOPCNTDQ,cpu-cpuid.CETSS,cpu-cpuid.CLZERO,cpu-cpuid.CMPXCHG8,cpu-cpuid.CPBOOST,cpu-cpuid.CPPC,cpu-cpuid.EFER_LMSLE_UNS,cpu-cpuid.FLUSH_L1D,cpu-cpuid.FMA3,cpu-cpuid.FP256,cpu-cpuid.FSRM,cpu-cpuid.FXSR,cpu-cpuid.FXSROPT,cpu-cpuid.GFNI,cpu-cpuid.IBPB,cpu-cpuid.IBRS,cpu-cpuid.IBRS_PREFERRED,cpu-cpuid.IBRS_PROVIDES_SMP,cpu-cpuid.IBS,cpu-cpuid.IBSBRNTRGT,cpu-cpuid.IBSFETCHSAM,cpu-cpuid.IBSFFV,cpu-cpuid.IBSOPCNT,cpu-cpuid.IBSOPCNTEXT,cpu-cpuid.IBSOPSAM,cpu-cpuid.IBSRDWROPCNT,cpu-cpuid.IBSRIPINVALIDCHK,cpu-cpuid.IBS_FETCH_CTLX,cpu-cpuid.IBS_OPFUSE,cpu-cpuid.IBS_PREVENTHOST,cpu-cpuid.IBS_ZEN4,cpu-cpuid.INT_WBINVD,cpu-cpuid.INVLPGB,cpu-cpuid.LAHF,cpu-cpuid.LBRVIRT,cpu-cpuid.MCAOVERFLOW,cpu-cpuid.MOVBE,cpu-cpuid.MOVU,cpu-cpuid.MSRIRC,cpu-cpuid.NRIPS,cpu-cpuid.OSXSAVE,cpu-cpuid.PPIN,cpu-cpuid.PSFD,cpu-cpuid.RDPRU,cpu-cpuid.SEV,cpu-cpuid.SEV_64BIT,cpu-cpuid.SEV_ALTERNATIVE,cpu-cpuid.SEV_DEBUGSWAP,cpu-cpuid.SEV_ES,cpu-cpuid.SEV_RESTRICTED,cpu-cpuid.SEV_SNP,cpu-cpuid.SHA,cpu-cpuid.SME,cpu-cpuid.SME_COHERENT,cpu-cpuid.SPEC_CTRL_SSBD,cpu-cpuid.SSE4A,cpu-cpuid.STIBP,cpu-cpuid.STIBP_ALWAYSON,cpu-cpuid.SUCCOR,cpu-cpuid.SVM,cpu-cpuid.SVMDA,cpu-cpuid.SVMFBASID,cpu-cpuid.SVML,cpu-cpuid.SVMNP,cpu-cpuid.SVMPF,cpu-cpuid.SVMPFT,cpu-cpuid.SYSCALL,cpu-cpuid.SYSEE,cpu-cpuid.TLB_FLUSH_NESTED,cpu-cpuid.TOPEXT,cpu-cpuid.TSCRATEMSR,cpu-cpuid.VAES,cpu-cpuid.VMCBCLEAN,cpu-cpuid.VMPL,cpu-cpuid.VMSA_REGPROT,cpu-cpuid.VPCLMULQDQ,cpu-cpuid.VTE,cpu-cpuid.WBNOINVD,cpu-cpuid.X87,cpu-cpuid.XGETBV1,cpu-cpuid.XSAVE,cpu-cpuid.XSAVEC,cpu-cpuid.XSAVEOPT,cpu-cpuid.XSAVES,cpu-hardware_multithreading,cpu-model.family,cpu-model.id,cpu-model.vendor_id,kernel-config.NO_HZ,kernel-config.NO_HZ_FULL,kernel-version.full,kernel-version.major,kernel-version.minor,kernel-version.revision,memory-numa,network-sriov.capable,pci-0300_1a03.present,pci-1200_1eff.present,pci-1200_1eff.sriov.capable,pci-1a03.present,pci-8086.present,pci-8086.sriov.capable,storage-nonrotationaldisk,system-os_release.ID,system-os_release.VERSION_ID,system-os_release.VERSION_ID.major,system-os_release.VERSION_ID.minor,usb-ef_0b1f_03ee.present
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 10.254.202.111/24
    projectcalico.org/IPv4VXLANTunnelAddr: 10.233.97.131
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-04-29T01:06:27Z"
  labels:
    accelerator-count: "2"
    accelerator-type: npu
    benchmark.openkcloud.io/role: benchmark-worker
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AMXFP8: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512BF16: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512BITALG: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512CD: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512F: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512IFMA: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI2: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VL: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VPOPCNTDQ: "true"
    feature.node.kubernetes.io/cpu-cpuid.CETSS: "true"
    feature.node.kubernetes.io/cpu-cpuid.CLZERO: "true"
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
    feature.node.kubernetes.io/cpu-cpuid.CPBOOST: "true"
    feature.node.kubernetes.io/cpu-cpuid.CPPC: "true"
    feature.node.kubernetes.io/cpu-cpuid.EFER_LMSLE_UNS: "true"
    feature.node.kubernetes.io/cpu-cpuid.FLUSH_L1D: "true"
    feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
    feature.node.kubernetes.io/cpu-cpuid.FP256: "true"
    feature.node.kubernetes.io/cpu-cpuid.FSRM: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.GFNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBPB: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBRS: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBRS_PREFERRED: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBRS_PROVIDES_SMP: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBS: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBS_FETCH_CTLX: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBS_OPFUSE: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBS_PREVENTHOST: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBS_ZEN4: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSBRNTRGT: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSFETCHSAM: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSFFV: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSOPCNT: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSOPCNTEXT: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSOPSAM: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSRDWROPCNT: "true"
    feature.node.kubernetes.io/cpu-cpuid.IBSRIPINVALIDCHK: "true"
    feature.node.kubernetes.io/cpu-cpuid.INT_WBINVD: "true"
    feature.node.kubernetes.io/cpu-cpuid.INVLPGB: "true"
    feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
    feature.node.kubernetes.io/cpu-cpuid.LBRVIRT: "true"
    feature.node.kubernetes.io/cpu-cpuid.MCAOVERFLOW: "true"
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
    feature.node.kubernetes.io/cpu-cpuid.MOVU: "true"
    feature.node.kubernetes.io/cpu-cpuid.MSRIRC: "true"
    feature.node.kubernetes.io/cpu-cpuid.NRIPS: "true"
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.PPIN: "true"
    feature.node.kubernetes.io/cpu-cpuid.PSFD: "true"
    feature.node.kubernetes.io/cpu-cpuid.RDPRU: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_64BIT: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_ALTERNATIVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_DEBUGSWAP: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_ES: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_RESTRICTED: "true"
    feature.node.kubernetes.io/cpu-cpuid.SEV_SNP: "true"
    feature.node.kubernetes.io/cpu-cpuid.SHA: "true"
    feature.node.kubernetes.io/cpu-cpuid.SME: "true"
    feature.node.kubernetes.io/cpu-cpuid.SME_COHERENT: "true"
    feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD: "true"
    feature.node.kubernetes.io/cpu-cpuid.SSE4A: "true"
    feature.node.kubernetes.io/cpu-cpuid.STIBP: "true"
    feature.node.kubernetes.io/cpu-cpuid.STIBP_ALWAYSON: "true"
    feature.node.kubernetes.io/cpu-cpuid.SUCCOR: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVM: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVMDA: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVMFBASID: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVML: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVMNP: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVMPF: "true"
    feature.node.kubernetes.io/cpu-cpuid.SVMPFT: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
    feature.node.kubernetes.io/cpu-cpuid.TLB_FLUSH_NESTED: "true"
    feature.node.kubernetes.io/cpu-cpuid.TOPEXT: "true"
    feature.node.kubernetes.io/cpu-cpuid.TSCRATEMSR: "true"
    feature.node.kubernetes.io/cpu-cpuid.VAES: "true"
    feature.node.kubernetes.io/cpu-cpuid.VMCBCLEAN: "true"
    feature.node.kubernetes.io/cpu-cpuid.VMPL: "true"
    feature.node.kubernetes.io/cpu-cpuid.VMSA_REGPROT: "true"
    feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ: "true"
    feature.node.kubernetes.io/cpu-cpuid.VTE: "true"
    feature.node.kubernetes.io/cpu-cpuid.WBNOINVD: "true"
    feature.node.kubernetes.io/cpu-cpuid.X87: "true"
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
    feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
    feature.node.kubernetes.io/cpu-model.family: "25"
    feature.node.kubernetes.io/cpu-model.id: "17"
    feature.node.kubernetes.io/cpu-model.vendor_id: AMD
    feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
    feature.node.kubernetes.io/kernel-config.NO_HZ_FULL: "true"
    feature.node.kubernetes.io/kernel-version.full: 6.8.0-40-generic
    feature.node.kubernetes.io/kernel-version.major: "6"
    feature.node.kubernetes.io/kernel-version.minor: "8"
    feature.node.kubernetes.io/kernel-version.revision: "0"
    feature.node.kubernetes.io/memory-numa: "true"
    feature.node.kubernetes.io/network-sriov.capable: "true"
    feature.node.kubernetes.io/pci-1a03.present: "true"
    feature.node.kubernetes.io/pci-0300_1a03.present: "true"
    feature.node.kubernetes.io/pci-1200_1eff.present: "true"
    feature.node.kubernetes.io/pci-1200_1eff.sriov.capable: "true"
    feature.node.kubernetes.io/pci-8086.present: "true"
    feature.node.kubernetes.io/pci-8086.sriov.capable: "true"
    feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
    feature.node.kubernetes.io/system-os_release.ID: ubuntu
    feature.node.kubernetes.io/system-os_release.VERSION_ID: "22.04"
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: "22"
    feature.node.kubernetes.io/system-os_release.VERSION_ID.minor: "04"
    feature.node.kubernetes.io/usb-ef_0b1f_03ee.present: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: node5
    kubernetes.io/os: linux
    npu-model: atomplus
    npu-vendor: rebellions
  name: node5
  resourceVersion: "17795129"
  uid: 4e3c7d74-645b-408e-b699-7994f19357d8
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2026-04-29T02:06:42Z"
  unschedulable: true
status:
  addresses:
  - address: 10.254.202.111
    type: InternalIP
  - address: node5
    type: Hostname
  allocatable:
    cpu: "96"
    ephemeral-storage: "846190708974"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 1584897864Ki
    pods: "110"
  capacity:
    cpu: "96"
    ephemeral-storage: 918175684Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 1585000264Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2026-04-29T01:31:59Z"
    lastTransitionTime: "2026-04-29T01:31:59Z"
    message: Calico is running on this node
    reason: CalicoIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2026-04-29T07:18:21Z"
    lastTransitionTime: "2026-04-29T01:06:27Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-04-29T07:18:21Z"
    lastTransitionTime: "2026-04-29T01:06:27Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-04-29T07:18:21Z"
    lastTransitionTime: "2026-04-29T01:06:27Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-04-29T07:18:21Z"
    lastTransitionTime: "2026-04-29T01:31:37Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - mcr.microsoft.com/playwright@sha256:98b1ad488de36b22d41fdd1b0c5b9cceaa78a8d2661c6ab02d2108a07c182338
    - mcr.microsoft.com/playwright:v1.49.0-jammy
    sizeBytes: 838422467
  - names:
    - quay.io/prometheus/prometheus@sha256:cd37346c974517be59bd528c43cfff51727fb75393df0ad8d10ce10013a047b6
    - quay.io/prometheus/prometheus:v3.11.2
    sizeBytes: 152918965
  - names:
    - docker.io/grafana/alloy@sha256:8c7256f412feb9f5f48f9f6f9394dc97ca887f63dea9304f347970ecc1787669
    - docker.io/grafana/alloy:v1.11.3
    sizeBytes: 150131069
  - names:
    - docker.io/jungwooshim/etri-llm-backend@sha256:226788475999176543994f5c73bb9f9125f812321ad722ce53429b539544afb1
    - docker.io/jungwooshim/etri-llm-backend:v15
    sizeBytes: 129203391
  - names:
    - quay.io/calico/node@sha256:d8c644a8a3eee06d88825b9a9fec6e7cd3b7c276d7f90afa8685a79fb300e7e3
    - quay.io/calico/node:v3.28.1
    sizeBytes: 117874046
  - names:
    - quay.io/calico/cni@sha256:e486870cfde8189f9ea145148bc353a2c0fca1f445213274023c1d11df69ae19
    - quay.io/calico/cni:v3.28.1
    sizeBytes: 94576755
  - names:
    - quay.io/calico/cni:v3.26.4
    sizeBytes: 93761170
  - names:
    - quay.io/calico/node:v3.26.4
    sizeBytes: 89478846
  - names:
    - registry.k8s.io/nfd/node-feature-discovery@sha256:9fb5b0764076a7e9c9a93579ef062dd7283b2db0253fa9f793a6931a2c88385e
    - registry.k8s.io/nfd/node-feature-discovery:v0.18.2
    sizeBytes: 84011971
  - names:
    - registry.k8s.io/nfd/node-feature-discovery@sha256:f9ef2ebee55141a1758d3c0a87bb701f5db2adf6856f7218b11bc2bac7b63862
    - registry.k8s.io/nfd/node-feature-discovery:v0.18.3
    sizeBytes: 83817218
  - names:
    - 10.254.202.100:5100/rebellions/k8s-device-plugin@sha256:6933e25bb6b760990a669c03304920ecda60c393b709767ed83174588ee03452
    - 10.254.202.100:5100/rebellions/k8s-device-plugin:v0.3.6
    sizeBytes: 67527253
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:a7bdabb683de10515e62b26da4cf36f52594b70ab00c245de730ae207163188f
    - 10.254.202.100:5100/npu-operator:v0.5.5-tt
    sizeBytes: 35413902
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:7e06ca76b9aebd1f9d4f3d36036bc35d80c1dd6aa3eb30a2d942d73788d29cd9
    - 10.254.202.100:5100/npu-operator:v0.5.7
    sizeBytes: 35395933
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:4bcd27b9c6c0215beb4ae595161dec1523bf6dfda911c4208a3a5935355f9cde
    - 10.254.202.100:5100/npu-operator:v0.5.6
    sizeBytes: 35395702
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:3a414c0f6f7bb8dea698ed8728ed522c2d0cb60fb8e155853d400b9935caeb35
    - 10.254.202.100:5100/npu-operator:v0.5.1-atom
    sizeBytes: 35390299
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:3d5b648c3dbfc0278a04638f3611ffd1809dc5ed6d730f22f8fa6d14d4ba4fc7
    - 10.254.202.100:5100/npu-operator:v0.5.3-atom
    sizeBytes: 35387282
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:bee84b618bed39b1fa7d1a934188eee5639f837f27d9a7ad5bc87a702a2c5f53
    - 10.254.202.100:5100/npu-operator:v0.5.2-atom
    sizeBytes: 35386500
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:5feb15c97b09ab971919900c99955185a45aacd0d22e0f357c59491f37f32c29
    - 10.254.202.100:5100/npu-operator:v0.5.4-nvrtc
    sizeBytes: 35383208
  - names:
    - 10.254.202.100:5100/npu-operator@sha256:a96d0a0b9816ebdae58861b02a7c5021709b872130b9f55eb7001b3d6c0573b5
    - 10.254.202.100:5100/npu-operator:v0.4.12-rngd
    sizeBytes: 35372042
  - names:
    - registry.k8s.io/dns/k8s-dns-node-cache:1.22.28
    sizeBytes: 34761701
  - names:
    - quay.io/calico/kube-controllers:v3.26.4
    sizeBytes: 32966765
  - names:
    - docker.io/library/ubuntu@sha256:962f6cadeae0ea6284001009daa4cc9a8c37e75d1f5191cf0eb83fe565b63dd7
    - docker.io/library/ubuntu:22.04
    sizeBytes: 29745662
  - names:
    - registry.k8s.io/kube-proxy@sha256:7dd7829fa889ac805a0b1047eba04599fa5006bdbcb5cb9c8d14e1dc8910488b
    - registry.k8s.io/kube-proxy:v1.28.12
    sizeBytes: 28302788
  - names:
    - docker.io/jungwooshim/etri-llm-frontend@sha256:41a93846c2a90c9579c5cf98527f8d7effcc64b93e7a793289d11d6b4419c225
    - docker.io/jungwooshim/etri-llm-frontend:v15
    sizeBytes: 27643176
  - names:
    - registry.k8s.io/kube-proxy@sha256:9e8b2882f54a0293a933066fee9ff9f6c4335a07637b7725e375b6a2ab00e215
    - registry.k8s.io/kube-proxy:v1.28.0
    sizeBytes: 24555100
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:f738e66c49c4e33b0c06776fb5e89617af5b1376e59dd58bbcbdb58ef99723a3
    - 10.254.202.100:5100/npu-detector:0.4.0
    sizeBytes: 21189699
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:5cdf64a7271b1ddb9da524d7d2be22a0104f2873373a2b37434aabcf4433a5c7
    - 10.254.202.100:5100/npu-detector:0.4.2
    sizeBytes: 21184675
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:a2c5dd62603901cb234755319b6aeef5a1fa8660df17ef307908cca98507f5c6
    - 10.254.202.100:5100/npu-detector:0.3.0
    sizeBytes: 21180649
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:0c6ed81d1248706b646c7161620bf58e73928e319d8cb7da67d7743c6418d244
    - 10.254.202.100:5100/npu-detector:0.4.1
    sizeBytes: 21179640
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:b40af33d9fa35618947a9c3ea4b1d893ba824883a3214968d828fc7158d95670
    - 10.254.202.100:5100/npu-detector:0.4.3
    sizeBytes: 21179452
  - names:
    - 10.254.202.100:5100/npu-detector@sha256:9c6ab9ae0eeafc011d9250c0532cecba113a36f67c80bf5e53c9535e651cb36f
    - 10.254.202.100:5100/npu-detector:0.2.2
    sizeBytes: 21171773
  - names:
    - docker.io/library/nginx:1.25.2-alpine
    sizeBytes: 17962407
  - names:
    - registry.k8s.io/coredns/coredns:v1.10.1
    sizeBytes: 16190758
  - names:
    - quay.io/prometheus-operator/prometheus-config-reloader@sha256:959d47672fbff2776a04ec62b8afcec89e8c036af84dc5fade50019dab212746
    - quay.io/prometheus-operator/prometheus-config-reloader:v0.81.0
    sizeBytes: 14433657
  - names:
    - quay.io/prometheus-operator/prometheus-config-reloader@sha256:693faa0b87243cddca2cffb13586e4e2778b0cdf319cb2e601ba7af3fd19ef7d
    - quay.io/prometheus-operator/prometheus-config-reloader:v0.90.1
    sizeBytes: 14230502
  - names:
    - quay.io/prometheus/node-exporter@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
    - quay.io/prometheus/node-exporter:v1.11.1
    sizeBytes: 13308798
  - names:
    - docker.io/curlimages/curl@sha256:c03110c736db81bbe1be0296f1f1608c81b954b01626bdfb0a8f84e5bd00ff3c
    - docker.io/curlimages/curl:latest
    sizeBytes: 10605753
  - names:
    - quay.io/calico/pod2daemon-flexvol:v3.26.4
    sizeBytes: 7466380
  - names:
    - quay.io/calico/pod2daemon-flexvol@sha256:76f6d9f7e6c393e53ae4c59b08e9b469f6253a364c0bc55e18c0338e44aab50d
    - quay.io/calico/pod2daemon-flexvol:v3.28.1
    sizeBytes: 6633986
  - names:
    - docker.io/library/busybox@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
    - docker.io/library/busybox:1.36
    sizeBytes: 2217006
  - names:
    - registry.k8s.io/pause:3.9
    sizeBytes: 321520
  - names:
    - registry.k8s.io/pause@sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d
    - registry.k8s.io/pause:3.8
    sizeBytes: 311286
  nodeInfo:
    architecture: amd64
    bootID: 177165b4-6b40-4649-9132-9903b7a6ce46
    containerRuntimeVersion: containerd://1.7.22
    kernelVersion: 6.8.0-40-generic
    kubeProxyVersion: v1.28.0
    kubeletVersion: v1.28.0
    machineID: 01546a16be5d42d0bd62325ef9b9d80e
    operatingSystem: linux
    osImage: Ubuntu 22.04.5 LTS
    systemUUID: 9d95b600-9bf2-11ef-8000-7cc25560b135
