apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: etri-llm-db
  name: etri-llm-db-service
  namespace: llm-evaluation
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: etri-llm-db      

---
apiVersion: v1
kind: Secret
metadata:
  name: etri-llm-db
  namespace: llm-evaluation
type: Opaque
stringData:
  DATABASE_HOST: db
  DATABASE_PORT: "5432"
  DATABASE_USER: postgres
  DATABASE_PASSWORD: <DB_PASSWORD>
  DATABASE_NAME: llmEvaluationDB
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: <DB_PASSWORD>
  POSTGRES_DB: llmEvaluationDB

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: llm-evaluation
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: postgres-pv-volume
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.254.184.195 
    path: /mnt/etri-llm-evaluation-postgres
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etri-llm-db
  namespace: llm-evaluation
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: etri-llm-db
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/instance: etri-llm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etri-llm-db
  replicas: 1      
  template:
    metadata:
      labels:
        app: etri-llm-db
        app.kubernetes.io/instance: etri-llm-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: etri-llm-db
          ports:
          - containerPort: 5432
            name: http
            protocol: TCP
          image: postgres:15.4-alpine
          envFrom:
          - secretRef:
              name: etri-llm-db
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
            readOnly: false
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
