{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .components.etriLLMFrontend.metadata.name }}
  namespace: {{ .global.namespace }}
  labels:
    app.kubernetes.io/name: etri-llm-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/instance: {{ .components.etriLLMFrontend.metadata.name }}
spec:
  selector:
    matchLabels:
      app: {{ .components.etriLLMFrontend.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .components.etriLLMFrontend.metadata.name }}
        app.kubernetes.io/instance: {{ .components.etriLLMFrontend.metadata.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .components.etriLLMFrontend.metadata.name }}
          ports:
          - containerPort: {{ .components.etriLLMFrontend.containers.containerPort }}
            name: http
            protocol: TCP
          image: {{ .components.etriLLMFrontend.containers.image }}
          envFrom:
          - secretRef:
              name: {{ .components.etriLLMFrontend.metadata.name }}
          imagePullPolicy: Always
      imagePullSecrets:
      - name: {{ .global.imagePullSecret.metadata.name }}
{{- end }}