#!/usr/bin/env bash
# 03_inventory_nodes.sh — collect live node facts and write a timestamped YAML report.
#
# Read-only: no mutations. Each run produces a new file:
#   reports/cluster_inventory_<timestamp>.yaml
# so prior runs are preserved.
#
# Collected per node:
#   hostname, OS, kernel, CPU count, RAM (MiB), swap status,
#   containerd version, GPU/NPU device presence, disk usage on /
#
# Usage:
#   ./03_inventory_nodes.sh [--dry-run] [--help]
#
# Exit codes:
#   0  inventory written
#   1  partial failure (some nodes unreachable)
#   2  user error

set -euo pipefail

case "${1:-}" in
  --help|-h)
    sed -n '/^#!/d; /^[^#]/q; s/^# \{0,1\}//; p' "$0"
    exit 0
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/common.sh
source "$SCRIPT_DIR/common.sh"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    *) die "Unknown flag '$1'. See --help." 2 ;;
  esac
done

log "=== 03_inventory_nodes: live cluster inventory ==="
log "RUN_ID=$RUN_ID  DRY_RUN=$DRY_RUN"

TIMESTAMP="$(date '+%Y%m%dT%H%M%S')"
REPORT_DIR="$REPO_ROOT/reports"
mkdir -p "$REPORT_DIR"
OUTPUT_FILE="$REPORT_DIR/cluster_inventory_${TIMESTAMP}.yaml"

FAIL=0

# Start YAML output
{
  printf '# cluster_inventory — generated by 03_inventory_nodes.sh\n'
  printf '# RUN_ID: %s\n' "$RUN_ID"
  printf '# timestamp: %s\n' "$TIMESTAMP"
  printf 'nodes:\n'
} > "$OUTPUT_FILE"

# ---------------------------------------------------------------------------
# collect_node NAME HOST PORT STATE ACCEL_TYPE ACCEL_VENDOR ACCEL_MODEL
# ---------------------------------------------------------------------------
collect_node() {
  local name="$1" host="$2" port="$3" state="$4"
  local accel_type="$5" accel_vendor="$6" accel_model="$7"

  if [ "$state" = "pending_join" ]; then
    log "  $name: SKIPPED (pending_join)"
    {
      printf '  - name: %s\n' "$name"
      printf '    state: pending_join\n'
      printf '    note: node not yet joined to cluster\n'
    } >> "$OUTPUT_FILE"
    return 0
  fi

  log "  Collecting $name ($host:$port) ..."

  if [ "$DRY_RUN" = "true" ]; then
    log "  [DRY-RUN] would SSH to $host:$port and collect facts"
    {
      printf '  - name: %s\n' "$name"
      printf '    state: dry_run\n'
      printf '    host: %s\n' "$host"
      printf '    port: %s\n' "$port"
    } >> "$OUTPUT_FILE"
    return 0
  fi

  local facts
  if ! facts="$(_ssh_cmd "$host" "$port" '
    echo "HOSTNAME=$(hostname)"
    echo "OS_NAME=$(grep ^PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d \")"
    echo "KERNEL=$(uname -r)"
    echo "ARCH=$(uname -m)"
    echo "CPU_CORES=$(nproc)"
    echo "RAM_MIB=$(awk "/^MemTotal/{printf \"%d\", \$2/1024}" /proc/meminfo)"
    echo "SWAP_ON=$(swapon --show 2>/dev/null | wc -l)"
    CTR=$(containerd --version 2>/dev/null | awk "{print \$3}" || echo "not_found")
    echo "CONTAINERD=$CTR"
    DISK=$(df -h / | awk "NR==2{print \$2\"|\"$3\"|\"$4\"|\"$5}")
    echo "DISK_ROOT=$DISK"
    GPU=$(command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1 || echo "none")
    echo "GPU=$GPU"
    FURIOSA=$(ls /dev/furiosa* 2>/dev/null | wc -l)
    echo "FURIOSA_DEVS=$FURIOSA"
  ' 2>&1)"; then
    log "  [FAIL] cannot SSH to $name"
    {
      printf '  - name: %s\n' "$name"
      printf '    state: unreachable\n'
      printf '    host: %s\n' "$host"
    } >> "$OUTPUT_FILE"
    FAIL=1
    return 1
  fi

  # Parse
  local hostname os_name kernel arch cpu ram swap_on containerd disk_root gpu furiosa_devs
  hostname="$(     printf '%s\n' "$facts" | grep '^HOSTNAME='     | cut -d= -f2)"
  os_name="$(      printf '%s\n' "$facts" | grep '^OS_NAME='      | cut -d= -f2-)"
  kernel="$(       printf '%s\n' "$facts" | grep '^KERNEL='       | cut -d= -f2)"
  arch="$(         printf '%s\n' "$facts" | grep '^ARCH='         | cut -d= -f2)"
  cpu="$(          printf '%s\n' "$facts" | grep '^CPU_CORES='    | cut -d= -f2)"
  ram="$(          printf '%s\n' "$facts" | grep '^RAM_MIB='      | cut -d= -f2)"
  swap_on="$(      printf '%s\n' "$facts" | grep '^SWAP_ON='      | cut -d= -f2)"
  containerd="$(   printf '%s\n' "$facts" | grep '^CONTAINERD='   | cut -d= -f2)"
  disk_root="$(    printf '%s\n' "$facts" | grep '^DISK_ROOT='    | cut -d= -f2)"
  gpu="$(          printf '%s\n' "$facts" | grep '^GPU='          | cut -d= -f2-)"
  furiosa_devs="$( printf '%s\n' "$facts" | grep '^FURIOSA_DEVS=' | cut -d= -f2)"

  local swap_status="off"
  [ "${swap_on:-0}" -gt 1 ] && swap_status="ON (warning)"

  {
    printf '  - name: %s\n'              "$name"
    printf '    state: active\n'
    printf '    host: %s\n'             "$host"
    printf '    port: %s\n'             "$port"
    printf '    hostname: %s\n'         "$hostname"
    printf '    os: "%s"\n'             "$os_name"
    printf '    kernel: %s\n'           "$kernel"
    printf '    arch: %s\n'             "$arch"
    printf '    cpu_cores: %s\n'        "$cpu"
    printf '    ram_mib: %s\n'          "$ram"
    printf '    swap: %s\n'             "$swap_status"
    printf '    containerd: %s\n'       "$containerd"
    printf '    disk_root: "%s"\n'      "$disk_root"
    printf '    accelerator:\n'
    printf '      type: %s\n'           "$accel_type"
    printf '      vendor: %s\n'         "$accel_vendor"
    printf '      model: "%s"\n'        "$accel_model"
    printf '      gpu_info: "%s"\n'     "$gpu"
    printf '      furiosa_dev_count: %s\n' "$furiosa_devs"
    printf '    collected_at: %s\n'     "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >> "$OUTPUT_FILE"

  log "  [OK]  $name: kernel=$kernel cpu=$cpu ram=${ram}MiB swap=$swap_status containerd=$containerd"
}

# ---------------------------------------------------------------------------
# Iterate nodes
# ---------------------------------------------------------------------------
python3 - "$REPO_ROOT/config/cluster.yaml" <<'PYEOF' | while IFS='|' read -r name role host port state accel_type accel_vendor accel_model; do
import yaml, sys
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
default_port = data.get('ssh', {}).get('default_port', 22)
all_nodes = []
for n in data.get('control_plane', []):
    all_nodes.append(n)
for n in data.get('workers', []):
    all_nodes.append(n)
for node in all_nodes:
    name   = node.get('name', '')
    role   = node.get('role', 'worker')
    host   = node.get('ssh', {}).get('host', '')
    port   = str(node.get('ssh', {}).get('port', default_port))
    state  = node.get('state', 'active')
    accel  = node.get('accelerator', {})
    atype  = accel.get('type', 'unknown')
    avendor= accel.get('vendor', 'unknown')
    amodel = accel.get('model', 'unknown')
    print(f"{name}|{role}|{host}|{port}|{state}|{atype}|{avendor}|{amodel}")
PYEOF
  collect_node "$name" "$host" "$port" "$state" "$accel_type" "$accel_vendor" "$accel_model"
done

log ""
log "Report written: $OUTPUT_FILE"
log "Note: this is READ-ONLY collection — no cluster state was modified."

if [ "$FAIL" -eq 0 ]; then
  log "=== 03_inventory_nodes: COMPLETE ==="
  exit 0
else
  log "=== 03_inventory_nodes: PARTIAL (some nodes unreachable) ==="
  exit 1
fi
