#!/usr/bin/env bash
# 04_label_and_taint_nodes.sh — apply node labels from cluster.yaml to the k8s cluster.
#
# Actions:
#   1. Backup existing node labels to backups/$RUN_ID/node-labels.json
#   2. Apply labels from cluster.yaml workers[].labels
#   3. Write a rollback script: backups/$RUN_ID/04_label_rollback.sh
#
# --dry-run outputs `kubectl label --dry-run=server` results without mutating.
#
# Usage:
#   ./04_label_and_taint_nodes.sh [--dry-run] [--help]
#
# Exit codes:
#   0  success
#   1  failure
#   2  user error

set -euo pipefail

case "${1:-}" in
  --help|-h)
    sed -n '/^#!/d; /^[^#]/q; s/^# \{0,1\}//; p' "$0"
    exit 0
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/common.sh
source "$SCRIPT_DIR/common.sh"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    *) die "Unknown flag '$1'. See --help." 2 ;;
  esac
done

log "=== 04_label_and_taint_nodes ==="
log "RUN_ID=$RUN_ID  DRY_RUN=$DRY_RUN"

BACKUP_DIR="$REPO_ROOT/backups/$RUN_ID"
mkdir -p "$BACKUP_DIR"

# ---------------------------------------------------------------------------
# 1. Backup existing labels
# ---------------------------------------------------------------------------
log "--- Step 1: backup existing node labels ---"
BACKUP_FILE="$BACKUP_DIR/node-labels.json"
ROLLBACK_FILE="$BACKUP_DIR/04_label_rollback.sh"

if [ "$DRY_RUN" = "true" ]; then
  log "  [DRY-RUN] would backup node labels to $BACKUP_FILE"
else
  kubectl get nodes -o json 2>/dev/null \
    | python3 -c "
import sys, json
data = json.load(sys.stdin)
out = {}
for item in data.get('items', []):
    name = item['metadata']['name']
    out[name] = item['metadata'].get('labels', {})
print(json.dumps(out, indent=2))
" > "$BACKUP_FILE" 2>/dev/null || {
    log "  [WARN] could not backup labels (kubectl unavailable?) — continuing"
  }
  log "  Backup written: $BACKUP_FILE"

  # Write rollback script
  {
    printf '#!/usr/bin/env bash\n'
    printf '# 04_label_rollback.sh — generated by 04_label_and_taint_nodes.sh\n'
    printf '# RUN_ID: %s\n' "$RUN_ID"
    printf '# Apply this to restore node labels to pre-run state.\n\n'
    printf 'set -euo pipefail\n\n'

    if [ -f "$BACKUP_FILE" ]; then
      python3 -c "
import json, sys
with open('$BACKUP_FILE') as f:
    data = json.load(f)
for node, labels in data.items():
    if labels:
        label_args = ' '.join(f'{k}={v}' for k,v in labels.items())
        print(f'kubectl label node {node} {label_args} --overwrite')
"
    else
      printf '# No backup labels file found at %s\n' "$BACKUP_FILE"
    fi
  } > "$ROLLBACK_FILE"
  chmod +x "$ROLLBACK_FILE"
  log "  Rollback script: $ROLLBACK_FILE"
fi

# ---------------------------------------------------------------------------
# 2. Apply labels from cluster.yaml
# ---------------------------------------------------------------------------
log "--- Step 2: apply node labels ---"

FAIL=0

python3 - "$REPO_ROOT/config/cluster.yaml" <<'PYEOF' | while IFS='|' read -r name state labels_json; do
import yaml, json, sys
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
all_nodes = list(data.get('control_plane', [])) + list(data.get('workers', []))
for node in all_nodes:
    name   = node.get('name', '')
    state  = node.get('state', 'active')
    labels = node.get('labels', {})
    print(f"{name}|{state}|{json.dumps(labels)}")
PYEOF
  if [ "$state" = "pending_join" ]; then
    log "  $name: SKIPPED (pending_join)"
    continue
  fi

  # Parse label JSON into key=value pairs
  LABEL_ARGS="$(python3 -c "
import json, sys
labels = json.loads(sys.argv[1])
print(' '.join(f'{k}={v}' for k,v in labels.items()))
" "$labels_json")"

  if [ -z "$LABEL_ARGS" ]; then
    log "  $name: no labels defined — skipping"
    continue
  fi

  log "  $name: applying labels: $LABEL_ARGS"

  if [ "$DRY_RUN" = "true" ]; then
    # shellcheck disable=SC2086
    kubectl label node "$name" $LABEL_ARGS --overwrite --dry-run=server 2>&1 \
      | while read -r line; do log "    [dry-run] $line"; done || {
      log "  [DRY-RUN] kubectl call failed (node may not be in cluster yet)"
    }
  else
    # shellcheck disable=SC2086
    if kubectl label node "$name" $LABEL_ARGS --overwrite 2>&1 \
        | while read -r line; do log "    $line"; done; then
      log "  [OK]  $name labels applied"
    else
      log "  [FAIL] $name label application failed"
      FAIL=1
    fi
  fi
done

log ""
if [ "$FAIL" -eq 0 ]; then
  if [ "$DRY_RUN" = "true" ]; then
    log "=== 04_label_and_taint_nodes: DRY-RUN COMPLETE (no mutations) ==="
  else
    log "=== 04_label_and_taint_nodes: COMPLETE [backup=$BACKUP_FILE rollback=$ROLLBACK_FILE] ==="
  fi
  exit 0
else
  log "=== 04_label_and_taint_nodes: FAILED on one or more nodes ==="
  exit 1
fi
