#!/usr/bin/env bash
# 06_prepare_rngd_npu_nodes.sh — verify/prepare FuriosaAI RNGD NPU on node4.
#
# Checks:
#   - furiosa device-plugin DaemonSet is present (kubectl get pods -n kube-system | grep furiosa)
#   - If missing: writes YAML to k8s/device-plugins/furiosa-rngd.yaml and emits "would apply"
#   - Does NOT apply unless --apply is passed
#   - With --apply: runs kubectl apply --dry-run=server first as a checkpoint, then applies
#
# Usage:
#   ./06_prepare_rngd_npu_nodes.sh [--dry-run] [--apply] [--help]
#
# Exit codes:
#   0  device-plugin present and healthy (or dry-run completed)
#   1  missing device-plugin (action required) or apply failed
#   2  user error

set -euo pipefail

case "${1:-}" in
  --help|-h)
    sed -n '/^#!/d; /^[^#]/q; s/^# \{0,1\}//; p' "$0"
    exit 0
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/common.sh
source "$SCRIPT_DIR/common.sh"

APPLY=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --apply)   APPLY=true;   shift ;;
    *) die "Unknown flag '$1'. See --help." 2 ;;
  esac
done

log "=== 06_prepare_rngd_npu_nodes ==="
log "RUN_ID=$RUN_ID  DRY_RUN=$DRY_RUN  APPLY=$APPLY"

DEVICE_PLUGIN_YAML="$REPO_ROOT/k8s/device-plugins/furiosa-rngd.yaml"
mkdir -p "$(dirname "$DEVICE_PLUGIN_YAML")"

FAIL=0

# ---------------------------------------------------------------------------
# 1. Check node4 is in cluster
# ---------------------------------------------------------------------------
log "--- Step 1: verify node4 is joined ---"
NODE4_NAME="$(python3 -c "
import yaml
with open('$REPO_ROOT/config/cluster.yaml') as f:
    data = yaml.safe_load(f)
for node in data.get('workers', []):
    if node.get('accelerator', {}).get('vendor') == 'furiosa' \
       and node.get('accelerator', {}).get('model', '').upper() == 'RNGD':
        print(node.get('name', 'node4'))
        break
" 2>/dev/null || echo "node4")"

if [ "$DRY_RUN" = "true" ]; then
  log "  [DRY-RUN] would verify $NODE4_NAME is in kubectl get nodes"
else
  if kubectl get node "$NODE4_NAME" >/dev/null 2>&1; then
    NODE4_STATUS="$(kubectl get node "$NODE4_NAME" --no-headers | awk '{print $2}')"
    log "  [OK]  $NODE4_NAME status: $NODE4_STATUS"
  else
    log "  [FAIL] $NODE4_NAME not found in cluster — run add-node.sh first"
    FAIL=1
  fi
fi

# ---------------------------------------------------------------------------
# 2. Check for furiosa device plugin
# ---------------------------------------------------------------------------
log "--- Step 2: check furiosa device-plugin DaemonSet ---"

FURIOSA_FOUND=false

if [ "$DRY_RUN" = "true" ]; then
  log "  [DRY-RUN] would check: kubectl get pods -n kube-system | grep furiosa"
else
  FURIOSA_PODS="$(kubectl get pods -n kube-system 2>/dev/null | grep -i furiosa || true)"
  if [ -n "$FURIOSA_PODS" ]; then
    FURIOSA_FOUND=true
    log "  [OK]  Furiosa device-plugin pods found:"
    printf '%s\n' "$FURIOSA_PODS" | while read -r line; do log "    $line"; done
  else
    log "  [WARN] No furiosa device-plugin pods found in kube-system"
    FURIOSA_FOUND=false
  fi
fi

# ---------------------------------------------------------------------------
# 3. If missing: write YAML scaffold
# ---------------------------------------------------------------------------
if [ "$FURIOSA_FOUND" = "false" ] || [ "$DRY_RUN" = "true" ]; then
  log "--- Step 3: write/update device-plugin YAML ---"

  # Write the device plugin manifest (idempotent)
  cat > "$DEVICE_PLUGIN_YAML" <<'YAML_EOF'
# furiosa-rngd.yaml — FuriosaAI RNGD NPU device plugin for Kubernetes
# Generated by: scripts/06_prepare_rngd_npu_nodes.sh
# Apply with: kubectl apply -f k8s/device-plugins/furiosa-rngd.yaml
#
# IMPORTANT: Verify the image tag against:
#   https://github.com/furiosa-ai/furiosa-device-plugin
# before applying to production.
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: furiosa-device-plugin
  namespace: kube-system
  labels:
    app: furiosa-device-plugin
    vendor: furiosa-ai
spec:
  selector:
    matchLabels:
      app: furiosa-device-plugin
  template:
    metadata:
      labels:
        app: furiosa-device-plugin
    spec:
      nodeSelector:
        npu-vendor: furiosa
      tolerations:
        - key: furiosa.ai/npu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      containers:
        - name: furiosa-device-plugin
          image: ghcr.io/furiosa-ai/furiosa-device-plugin:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
YAML_EOF

  log "  Device plugin YAML written: $DEVICE_PLUGIN_YAML"
fi

# ---------------------------------------------------------------------------
# 4. Apply logic
# ---------------------------------------------------------------------------
if [ "$FURIOSA_FOUND" = "false" ] && [ "$DRY_RUN" = "false" ]; then
  if [ "$APPLY" = "false" ]; then
    log ""
    log "  === ACTION REQUIRED ==="
    log "  Furiosa device-plugin is not installed."
    log "  YAML scaffold written to: $DEVICE_PLUGIN_YAML"
    log "  Review the YAML, update the image tag, then run:"
    log "    $0 --apply"
    log "  which will first run --dry-run=server as a checkpoint."
    log "  === END ACTION REQUIRED ==="
    FAIL=1
  else
    # --apply path: dry-run=server first
    log "--- Step 4: kubectl apply (--dry-run=server checkpoint) ---"
    if kubectl apply -f "$DEVICE_PLUGIN_YAML" --dry-run=server 2>&1 \
        | while read -r line; do log "  [dry-run=server] $line"; done; then
      log "  [OK]  server-side dry-run passed"
      log "--- Step 4b: kubectl apply (live) ---"
      if kubectl apply -f "$DEVICE_PLUGIN_YAML" 2>&1 \
          | while read -r line; do log "  [apply] $line"; done; then
        log "  [OK]  furiosa device-plugin applied"
      else
        log "  [FAIL] kubectl apply failed"
        FAIL=1
      fi
    else
      log "  [FAIL] server-side dry-run failed — not applying"
      FAIL=1
    fi
  fi
fi

log ""
if [ "$FAIL" -eq 0 ]; then
  log "=== 06_prepare_rngd_npu_nodes: COMPLETE [validated] ==="
  exit 0
else
  log "=== 06_prepare_rngd_npu_nodes: ACTION REQUIRED ==="
  exit 1
fi
