#!/usr/bin/env bash
# 07_prepare_atomplus_npu_nodes.sh — prepare Atom+ NPU on node5 (currently pending_join).
#
# Current state: node5 has state=pending_join in cluster.yaml.
# This script emits a graceful warning and exits 0.
#
# When node5 IS joined, this script will:
#   - Verify node5 is in the cluster
#   - Check for Atom+ device-plugin DaemonSet in kube-system
#   - If missing: write YAML to k8s/device-plugins/furiosa-atomplus.yaml
#   - --apply path: kubectl apply --dry-run=server checkpoint, then live apply
#
# Usage:
#   ./07_prepare_atomplus_npu_nodes.sh [--dry-run] [--apply] [--help]
#
# Exit codes:
#   0  node5 pending (expected) or Atom+ device-plugin healthy
#   1  node5 joined but device-plugin unhealthy and --apply failed
#   2  user error

set -euo pipefail

case "${1:-}" in
  --help|-h)
    sed -n '/^#!/d; /^[^#]/q; s/^# \{0,1\}//; p' "$0"
    exit 0
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/common.sh
source "$SCRIPT_DIR/common.sh"

APPLY=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --apply)   APPLY=true;   shift ;;
    *) die "Unknown flag '$1'. See --help." 2 ;;
  esac
done

log "=== 07_prepare_atomplus_npu_nodes ==="
log "RUN_ID=$RUN_ID  DRY_RUN=$DRY_RUN  APPLY=$APPLY"

DEVICE_PLUGIN_YAML="$REPO_ROOT/k8s/device-plugins/furiosa-atomplus.yaml"
mkdir -p "$(dirname "$DEVICE_PLUGIN_YAML")"

# ---------------------------------------------------------------------------
# 1. Detect node5 state from cluster.yaml
# ---------------------------------------------------------------------------
NODE5_INFO="$(python3 -c "
import yaml
with open('$REPO_ROOT/config/cluster.yaml') as f:
    data = yaml.safe_load(f)
for node in data.get('workers', []):
    accel = node.get('accelerator', {})
    if accel.get('vendor') == 'furiosa' and 'atom' in accel.get('model', '').lower():
        print(node.get('name', 'node5') + '|' + node.get('state', 'active'))
        break
else:
    print('node5|unknown')
" 2>/dev/null || echo "node5|unknown")"

NODE5_NAME="${NODE5_INFO%%|*}"
NODE5_STATE="${NODE5_INFO##*|}"

log "  node5 name=$NODE5_NAME  state_in_yaml=$NODE5_STATE"

# ---------------------------------------------------------------------------
# 2. If pending_join — emit graceful warning and exit 0
# ---------------------------------------------------------------------------
if [ "$NODE5_STATE" = "pending_join" ]; then
  log ""
  log "  === NODE5 STATUS: pending_join ==="
  log "  $NODE5_NAME has not yet been joined to the Kubernetes cluster."
  log "  This is expected. No action taken."
  log ""
  log "  When node5 is joined, run the following in order:"
  log "    1. scripts/add-node.sh $NODE5_NAME <ip> --port 22"
  log "    2. scripts/01_preflight_workers.sh  (verify prerequisites)"
  log "    3. scripts/04_label_and_taint_nodes.sh  (apply npu labels)"
  log "    4. scripts/07_prepare_atomplus_npu_nodes.sh --apply  (install device plugin)"
  log "  === END NODE5 STATUS ==="
  log ""
  log "=== 07_prepare_atomplus_npu_nodes: SKIPPED (state=pending_join) — exit 0 ==="
  exit 0
fi

# ---------------------------------------------------------------------------
# 3. Node5 IS joined — verify and configure Atom+ device plugin
# ---------------------------------------------------------------------------
log "--- Step 1: verify $NODE5_NAME is joined ---"
if [ "$DRY_RUN" = "true" ]; then
  log "  [DRY-RUN] would verify $NODE5_NAME in kubectl get nodes"
else
  if kubectl get node "$NODE5_NAME" >/dev/null 2>&1; then
    STATUS="$(kubectl get node "$NODE5_NAME" --no-headers | awk '{print $2}')"
    log "  [OK]  $NODE5_NAME status: $STATUS"
  else
    log "  [FAIL] $NODE5_NAME not found in cluster. State in cluster.yaml may be stale."
    exit 1
  fi
fi

# ---------------------------------------------------------------------------
# 4. Check Atom+ device plugin
# ---------------------------------------------------------------------------
log "--- Step 2: check Atom+ device-plugin DaemonSet ---"

ATOMPLUS_FOUND=false

if [ "$DRY_RUN" = "true" ]; then
  log "  [DRY-RUN] would check: kubectl get pods -n kube-system | grep furiosa"
else
  ATOMPLUS_PODS="$(kubectl get pods -n kube-system 2>/dev/null \
    | grep -i furiosa | grep -i atom || true)"
  if [ -n "$ATOMPLUS_PODS" ]; then
    ATOMPLUS_FOUND=true
    log "  [OK]  Atom+ device-plugin pods found:"
    printf '%s\n' "$ATOMPLUS_PODS" | while read -r line; do log "    $line"; done
  else
    log "  [WARN] No Atom+ device-plugin pods found in kube-system"
  fi
fi

# ---------------------------------------------------------------------------
# 5. Write YAML if missing
# ---------------------------------------------------------------------------
if [ "$ATOMPLUS_FOUND" = "false" ] || [ "$DRY_RUN" = "true" ]; then
  log "--- Step 3: write device-plugin YAML ---"

  cat > "$DEVICE_PLUGIN_YAML" <<'YAML_EOF'
# furiosa-atomplus.yaml — FuriosaAI Atom+ NPU device plugin for Kubernetes
# Generated by: scripts/07_prepare_atomplus_npu_nodes.sh
# Apply with: kubectl apply -f k8s/device-plugins/furiosa-atomplus.yaml
#
# IMPORTANT: Verify image tag against:
#   https://github.com/furiosa-ai/furiosa-device-plugin
# before applying to production. Atom+ support may require a specific release.
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: furiosa-atomplus-device-plugin
  namespace: kube-system
  labels:
    app: furiosa-atomplus-device-plugin
    vendor: furiosa-ai
    model: atom-plus
spec:
  selector:
    matchLabels:
      app: furiosa-atomplus-device-plugin
  template:
    metadata:
      labels:
        app: furiosa-atomplus-device-plugin
    spec:
      nodeSelector:
        npu-model: atomplus
      tolerations:
        - key: furiosa.ai/npu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      containers:
        - name: furiosa-atomplus-device-plugin
          image: ghcr.io/furiosa-ai/furiosa-device-plugin:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NPU_MODEL
              value: atom-plus
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
YAML_EOF

  log "  Device plugin YAML written: $DEVICE_PLUGIN_YAML"
fi

# ---------------------------------------------------------------------------
# 6. Apply logic
# ---------------------------------------------------------------------------
FAIL=0
if [ "$ATOMPLUS_FOUND" = "false" ] && [ "$DRY_RUN" = "false" ]; then
  if [ "$APPLY" = "false" ]; then
    log ""
    log "  === ACTION REQUIRED ==="
    log "  Atom+ device-plugin is not installed."
    log "  YAML scaffold written to: $DEVICE_PLUGIN_YAML"
    log "  Review/update the image tag, then run:"
    log "    $0 --apply"
    log "  === END ACTION REQUIRED ==="
    FAIL=1
  else
    log "--- Step 4: kubectl apply (--dry-run=server checkpoint) ---"
    if kubectl apply -f "$DEVICE_PLUGIN_YAML" --dry-run=server 2>&1 \
        | while read -r line; do log "  [dry-run=server] $line"; done; then
      log "  [OK]  server-side dry-run passed"
      log "--- Step 4b: kubectl apply (live) ---"
      if kubectl apply -f "$DEVICE_PLUGIN_YAML" 2>&1 \
          | while read -r line; do log "  [apply] $line"; done; then
        log "  [OK]  Atom+ device-plugin applied"
      else
        log "  [FAIL] kubectl apply failed"
        FAIL=1
      fi
    else
      log "  [FAIL] server-side dry-run failed — not applying"
      FAIL=1
    fi
  fi
fi

log ""
if [ "$FAIL" -eq 0 ]; then
  log "=== 07_prepare_atomplus_npu_nodes: COMPLETE [validated] ==="
  exit 0
else
  log "=== 07_prepare_atomplus_npu_nodes: ACTION REQUIRED ==="
  exit 1
fi
