FROM node:22-alpine AS builder

WORKDIR /usr/src/app
COPY package*.json yarn.lock ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
